import { createUniqueId } from "solid-js";
export type CarSpecifications = {
  brand: string;
  models: {
    id: string
    name: string;
    transmission: string;
    fuelType: string;
    seatNumbers: number;
    condition: string;
    price: number;
    rentPrice: number;
  }[];
};
const CarSpecifications: CarSpecifications[] = [
  {
    brand: "Toyota",
    models: [
      {
        id: createUniqueId(),
        name: "Camry",
        transmission: "Automatic",
        fuelType: "Petrol",
        seatNumbers: 5,
        condition: "New",
        price: 25000,
        rentPrice: 150,
      },
      {
        id: createUniqueId(),
        name: "Corolla",
        transmission: "Manual",
        fuelType: "Petrol",
        seatNumbers: 5,
        condition: "Used",
        price: 15000,
        rentPrice: 100,
      },
      {
        id: createUniqueId(),
        name: "RAV4",
        transmission: "Automatic",
        fuelType: "Petrol",
        seatNumbers: 5,
        condition: "Used",
        price: 20000,
        rentPrice: 120,
      },
      {
        id: createUniqueId(),
        name: "Highlander",
        transmission: "Automatic",
        fuelType: "Hybrid",
        seatNumbers: 7,
        condition: "New",
        price: 35000,
        rentPrice: 200,
      },
      {
        id: createUniqueId(),
        name: "Prius",
        transmission: "Automatic",
        fuelType: "Hybrid",
        seatNumbers: 5,
        condition: "Used",
        price: 18000,
        rentPrice: 110,
      },
    ],
  },
  {
    brand: "Honda",
    models: [
      {
        id: createUniqueId(),
        name: "Civic",
        transmission: "Automatic",
        fuelType: "Petrol",
        seatNumbers: 5,
        condition: "New",
        price: 22000,
        rentPrice: 130,
      },
      {
        id: createUniqueId(),
        name: "Accord",
        transmission: "Automatic",
        fuelType: "Petrol",
        seatNumbers: 5,
        condition: "Used",
        price: 18000,
        rentPrice: 110,
      },
      {
        id: createUniqueId(),
        name: "CR-V",
        transmission: "Automatic",
        fuelType: "Petrol",
        seatNumbers: 5,
        condition: "Used",
        price: 25000,
        rentPrice: 150,
      },
      {
        id: createUniqueId(),
        name: "Pilot",
        transmission: "Automatic",
        fuelType: "Petrol",
        seatNumbers: 8,
        condition: "New",
        price: 35000,
        rentPrice: 200,
      },
      {
        id: createUniqueId(),
        name: "Odyssey",
        transmission: "Automatic",
        fuelType: "Diesel",
        seatNumbers: 7,
        condition: "Used",
        price: 30000,
        rentPrice: 180,
      },
    ],
  },
  {
    brand: "Ford",
    models: [
      {
        id: createUniqueId(),
        name: "F-150",
        transmission: "Automatic",
        fuelType: "Petrol",
        seatNumbers: 6,
        condition: "New",
        price: 40000,
        rentPrice: 220,
      },
      {
        id: createUniqueId(),
        name: "Mustang",
        transmission: "Manual",
        fuelType: "Petrol",
        seatNumbers: 4,
        condition: "Used",
        price: 30000,
        rentPrice: 170,
      },
      {
        id: createUniqueId(),
        name: "Explorer",
        transmission: "Automatic",
        fuelType: "Petrol",
        seatNumbers: 7,
        condition: "Used",
        price: 35000,
        rentPrice: 190,
      },
      {
        id: createUniqueId(),
        name: "Escape",
        transmission: "Automatic",
        fuelType: "Petrol",
        seatNumbers: 5,
        condition: "New",
        price: 25000,
        rentPrice: 150,
      },
      {
        id: createUniqueId(),
        name: "Focus",
        transmission: "Automatic",
        fuelType: "Petrol",
        seatNumbers: 5,
        condition: "Used",
        price: 20000,
        rentPrice: 120,
      },
    ],
  },
  {
    brand: "Chevrolet",
    models: [
      {
        id: createUniqueId(),
        name: "Silverado",
        transmission: "Automatic",
        fuelType: "Petrol",
        seatNumbers: 5,
        condition: "New",
        price: 40000,
        rentPrice: 220,
      },
      {
        id: createUniqueId(),
        name: "Camaro",
        transmission: "Manual",
        fuelType: "Petrol",
        seatNumbers: 4,
        condition: "Used",
        price: 35000,
        rentPrice: 190,
      },
      {
        id: createUniqueId(),
        name: "Equinox",
        transmission: "Automatic",
        fuelType: "Petrol",
        seatNumbers: 5,
        condition: "Used",
        price: 30000,
        rentPrice: 180,
      },
      {
        id: createUniqueId(),
        name: "Traverse",
        transmission: "Automatic",
        fuelType: "Petrol",
        seatNumbers: 7,
        condition: "New",
        price: 45000,
        rentPrice: 250,
      },
      {
        id: createUniqueId(),
        name: "Malibu",
        transmission: "Automatic",
        fuelType: "Petrol",
        seatNumbers: 5,
        condition: "Used",
        price: 25000,
        rentPrice: 150,
      },
    ],
  },
  {
    brand: "Volkswagen",
    models: [
      {
        id: createUniqueId(),
        name: "Golf",
        transmission: "Automatic",
        fuelType: "Petrol",
        seatNumbers: 5,
        condition: "New",
        price: 22000,
        rentPrice: 130,
      },
      {
        id: createUniqueId(),
        name: "Passat",
        transmission: "Automatic",
        fuelType: "Petrol",
        seatNumbers: 5,
        condition: "Used",
        price: 20000,
        rentPrice: 120,
      },
      {
        id: createUniqueId(),
        name: "Tiguan",
        transmission: "Automatic",
        fuelType: "Petrol",
        seatNumbers: 5,
        condition: "Used",
        price: 25000,
        rentPrice: 150,
      },
      {
        id: createUniqueId(),
        name: "Jetta",
        transmission: "Automatic",
        fuelType: "Petrol",
        seatNumbers: 5,
        condition: "New",
        price: 23000,
        rentPrice: 140,
      },
      {
        id: createUniqueId(),
        name: "Atlas",
        transmission: "Automatic",
        fuelType: "Petrol",
        seatNumbers: 7,
        condition: "Used",
        price: 35000,
        rentPrice: 200,
      },
    ],
  },
  {
    brand: "BMW",
    models: [
      {
        id: createUniqueId(),
        name: "3 Series",
        transmission: "Automatic",
        fuelType: "Petrol",
        seatNumbers: 5,
        condition: "New",
        price: 40000,
        rentPrice: 220,
      },
      {
        id: createUniqueId(),
        name: "5 Series",
        transmission: "Automatic",
        fuelType: "Petrol",
        seatNumbers: 5,
        condition: "Used",
        price: 50000,
        rentPrice: 280,
      },
      {
        id: createUniqueId(),
        name: "X3",
        transmission: "Automatic",
        fuelType: "Petrol",
        seatNumbers: 5,
        condition: "Used",
        price: 45000,
        rentPrice: 250,
      },
      {
        id: createUniqueId(),
        name: "X5",
        transmission: "Automatic",
        fuelType: "Petrol",
        seatNumbers: 7,
        condition: "New",
        price: 60000,
        rentPrice: 350,
      },
      {
        id: createUniqueId(),
        name: "i8",
        transmission: "Automatic",
        fuelType: "Electric",
        seatNumbers: 2,
        condition: "Used",
        price: 100000,
        rentPrice: 500,
      },
    ],
  },
  {
    brand: "Mercedes-Benz",
    models: [
      {
        id: createUniqueId(),
        name: "C-Class",
        transmission: "Automatic",
        fuelType: "Petrol",
        seatNumbers: 5,
        condition: "New",
        price: 45000,
        rentPrice: 250,
      },
      {
        id: createUniqueId(),
        name: "E-Class",
        transmission: "Automatic",
        fuelType: "Petrol",
        seatNumbers: 5,
        condition: "Used",
        price: 55000,
        rentPrice: 320,
      },
      {
        id: createUniqueId(),
        name: "GLC",
        transmission: "Automatic",
        fuelType: "Petrol",
        seatNumbers: 5,
        condition: "Used",
        price: 50000,
        rentPrice: 280,
      },
      {
        id: createUniqueId(),
        name: "GLE",
        transmission: "Automatic",
        fuelType: "Petrol",
        seatNumbers: 7,
        condition: "New",
        price: 65000,
        rentPrice: 380,
      },
      {
        id: createUniqueId(),
        name: "S-Class",
        transmission: "Automatic",
        fuelType: "Petrol",
        seatNumbers: 5,
        condition: "Used",
        price: 80000,
        rentPrice: 450,
      },
    ],
  },
  {
    brand: "Audi",
    models: [
      {
        id: createUniqueId(),
        name: "A4",
        transmission: "Automatic",
        fuelType: "Petrol",
        seatNumbers: 5,
        condition: "New",
        price: 40000,
        rentPrice: 220,
      },
      {
        id: createUniqueId(),
        name: "A6",
        transmission: "Automatic",
        fuelType: "Petrol",
        seatNumbers: 5,
        condition: "Used",
        price: 50000,
        rentPrice: 280,
      },
      {
        id: createUniqueId(),
        name: "Q5",
        transmission: "Automatic",
        fuelType: "Petrol",
        seatNumbers: 5,
        condition: "Used",
        price: 45000,
        rentPrice: 250,
      },
      {
        id: createUniqueId(),
        name: "Q7",
        transmission: "Automatic",
        fuelType: "Petrol",
        seatNumbers: 7,
        condition: "New",
        price: 60000,
        rentPrice: 350,
      },
      {
        id: createUniqueId(),
        name: "TT",
        transmission: "Automatic",
        fuelType: "Petrol",
        seatNumbers: 2,
        condition: "Used",
        price: 50000,
        rentPrice: 280,
      },
    ],
  },
  {
    brand: "Lexus",
    models: [
      {
        id: createUniqueId(),
        name: "ES",
        transmission: "Automatic",
        fuelType: "Petrol",
        seatNumbers: 5,
        condition: "New",
        price: 45000,
        rentPrice: 250,
      },
      {
        id: createUniqueId(),
        name: "RX",
        transmission: "Automatic",
        fuelType: "Petrol",
        seatNumbers: 5,
        condition: "Used",
        price: 55000,
        rentPrice: 320,
      },
      {
        id: createUniqueId(),
        name: "NX",
        transmission: "Automatic",
        fuelType: "Petrol",
        seatNumbers: 5,
        condition: "Used",
        price: 50000,
        rentPrice: 280,
      },
      {
        id: createUniqueId(),
        name: "LS",
        transmission: "Automatic",
        fuelType: "Petrol",
        seatNumbers: 5,
        condition: "New",
        price: 65000,
        rentPrice: 380,
      },
      {
        id: createUniqueId(),
        name: "GX",
        transmission: "Automatic",
        fuelType: "Petrol",
        seatNumbers: 7,
        condition: "Used",
        price: 80000,
        rentPrice: 450,
      },
    ],
  },
  {
    brand: "Nissan",
    models: [
      {
        id: createUniqueId(),
        name: "Altima",
        transmission: "Automatic",
        fuelType: "Petrol",
        seatNumbers: 5,
        condition: "New",
        price: 22000,
        rentPrice: 130,
      },
      {
        id: createUniqueId(),
        name: "Maxima",
        transmission: "Automatic",
        fuelType: "Petrol",
        seatNumbers: 5,
        condition: "Used",
        price: 25000,
        rentPrice: 150,
      },
      {
        id: createUniqueId(),
        name: "Rogue",
        transmission: "Automatic",
        fuelType: "Petrol",
        seatNumbers: 5,
        condition: "Used",
        price: 30000,
        rentPrice: 180,
      },
      {
        id: createUniqueId(),
        name: "Pathfinder",
        transmission: "Automatic",
        fuelType: "Petrol",
        seatNumbers: 7,
        condition: "New",
        price: 35000,
        rentPrice: 200,
      },
      {
        id: createUniqueId(),
        name: "Frontier",
        transmission: "Automatic",
        fuelType: "Petrol",
        seatNumbers: 5,
        condition: "Used",
        price: 28000,
        rentPrice: 160,
      },
    ],
  },
  {
    brand: "Mazda",
    models: [
      {
        id: createUniqueId(),
        name: "Mazda3",
        transmission: "Automatic",
        fuelType: "Petrol",
        seatNumbers: 5,
        condition: "New",
        price: 23000,
        rentPrice: 140,
      },
      {
        id: createUniqueId(),
        name: "Mazda6",
        transmission: "Automatic",
        fuelType: "Petrol",
        seatNumbers: 5,
        condition: "Used",
        price: 26000,
        rentPrice: 160,
      },
      {
        id: createUniqueId(),
        name: "CX-5",
        transmission: "Automatic",
        fuelType: "Petrol",
        seatNumbers: 5,
        condition: "Used",
        price: 30000,
        rentPrice: 180,
      },
      {
        id: createUniqueId(),
        name: "CX-9",
        transmission: "Automatic",
        fuelType: "Petrol",
        seatNumbers: 7,
        condition: "New",
        price: 40000,
        rentPrice: 240,
      },
      {
        id: createUniqueId(),
        name: "MX-5",
        transmission: "Manual",
        fuelType: "Petrol",
        seatNumbers: 2,
        condition: "Used",
        price: 35000,
        rentPrice: 200,
      },
    ],
  },
  {
    brand: "Hyundai",
    models: [
      {
        id: createUniqueId(),
        name: "Elantra",
        transmission: "Automatic",
        fuelType: "Petrol",
        seatNumbers: 5,
        condition: "New",
        price: 22000,
        rentPrice: 130,
      },
      {
        id: createUniqueId(),
        name: "Sonata",
        transmission: "Automatic",
        fuelType: "Petrol",
        seatNumbers: 5,
        condition: "Used",
        price: 25000,
        rentPrice: 150,
      },
      {
        id: createUniqueId(),
        name: "Tucson",
        transmission: "Automatic",
        fuelType: "Petrol",
        seatNumbers: 5,
        condition: "Used",
        price: 28000,
        rentPrice: 160,
      },
      {
        id: createUniqueId(),
        name: "Santa Fe",
        transmission: "Automatic",
        fuelType: "Petrol",
        seatNumbers: 7,
        condition: "New",
        price: 38000,
        rentPrice: 220,
      },
      {
        id: createUniqueId(),
        name: "Kona",
        transmission: "Automatic",
        fuelType: "Petrol",
        seatNumbers: 5,
        condition: "Used",
        price: 26000,
        rentPrice: 160,
      },
    ],
  },
  {
    brand: "Kia",
    models: [
      {
        id: createUniqueId(),
        name: "Optima",
        transmission: "Automatic",
        fuelType: "Petrol",
        seatNumbers: 5,
        condition: "New",
        price: 23000,
        rentPrice: 140,
      },
      {
        id: createUniqueId(),
        name: "Sorento",
        transmission: "Automatic",
        fuelType: "Petrol",
        seatNumbers: 7,
        condition: "Used",
        price: 35000,
        rentPrice: 200,
      },
      {
        id: createUniqueId(),
        name: "Sportage",
        transmission: "Automatic",
        fuelType: "Petrol",
        seatNumbers: 5,
        condition: "Used",
        price: 28000,
        rentPrice: 160,
      },
      {
        id: createUniqueId(),
        name: "Telluride",
        transmission: "Automatic",
        fuelType: "Petrol",
        seatNumbers: 8,
        condition: "New",
        price: 40000,
        rentPrice: 240,
      },
      {
        id: createUniqueId(),
        name: "Forte",
        transmission: "Automatic",
        fuelType: "Petrol",
        seatNumbers: 5,
        condition: "Used",
        price: 22000,
        rentPrice: 130,
      },
    ],
  },
  {
    brand: "Subaru",
    models: [
      {
        id: createUniqueId(),
        name: "Impreza",
        transmission: "Automatic",
        fuelType: "Petrol",
        seatNumbers: 5,
        condition: "New",
        price: 24000,
        rentPrice: 150,
      },
      {
        id: createUniqueId(),
        name: "Outback",
        transmission: "Automatic",
        fuelType: "Petrol",
        seatNumbers: 5,
        condition: "Used",
        price: 30000,
        rentPrice: 180,
      },
      {
        id: createUniqueId(),
        name: "Forester",
        transmission: "Automatic",
        fuelType: "Petrol",
        seatNumbers: 5,
        condition: "Used",
        price: 28000,
        rentPrice: 160,
      },
      {
        id: createUniqueId(),
        name: "Legacy",
        transmission: "Automatic",
        fuelType: "Petrol",
        seatNumbers: 5,
        condition: "New",
        price: 32000,
        rentPrice: 200,
      },
      {
        id: createUniqueId(),
        name: "Crosstrek",
        transmission: "Automatic",
        fuelType: "Petrol",
        seatNumbers: 5,
        condition: "Used",
        price: 26000,
        rentPrice: 160,
      },
    ],
  },
  {
    brand: "Jeep",
    models: [
      {
        id: createUniqueId(),
        name: "Wrangler",
        transmission: "Manual",
        fuelType: "Petrol",
        seatNumbers: 4,
        condition: "New",
        price: 35000,
        rentPrice: 220,
      },
      {
        id: createUniqueId(),
        name: "Cherokee",
        transmission: "Automatic",
        fuelType: "Petrol",
        seatNumbers: 5,
        condition: "Used",
        price: 30000,
        rentPrice: 180,
      },
      {
        id: createUniqueId(),
        name: "Grand Cherokee",
        transmission: "Automatic",
        fuelType: "Petrol",
        seatNumbers: 5,
        condition: "Used",
        price: 38000,
        rentPrice: 240,
      },
      {
        id: createUniqueId(),
        name: "Renegade",
        transmission: "Automatic",
        fuelType: "Petrol",
        seatNumbers: 5,
        condition: "New",
        price: 25000,
        rentPrice: 150,
      },
      {
        id: createUniqueId(),
        name: "Compass",
        transmission: "Automatic",
        fuelType: "Petrol",
        seatNumbers: 5,
        condition: "Used",
        price: 27000,
        rentPrice: 170,
      },
    ],
  },
  {
    brand: "Volvo",
    models: [
      {
        id: createUniqueId(),
        name: "S60",
        transmission: "Automatic",
        fuelType: "Petrol",
        seatNumbers: 5,
        condition: "New",
        price: 38000,
        rentPrice: 240,
      },
      {
        id: createUniqueId(),
        name: "S90",
        transmission: "Automatic",
        fuelType: "Petrol",
        seatNumbers: 5,
        condition: "Used",
        price: 45000,
        rentPrice: 280,
      },
      {
        id: createUniqueId(),
        name: "XC40",
        transmission: "Automatic",
        fuelType: "Petrol",
        seatNumbers: 5,
        condition: "Used",
        price: 40000,
        rentPrice: 250,
      },
      {
        id: createUniqueId(),
        name: "XC60",
        transmission: "Automatic",
        fuelType: "Petrol",
        seatNumbers: 5,
        condition: "New",
        price: 48000,
        rentPrice: 300,
      },
      {
        id: createUniqueId(),
        name: "XC90",
        transmission: "Automatic",
        fuelType: "Petrol",
        seatNumbers: 7,
        condition: "Used",
        price: 52000,
        rentPrice: 320,
      },
    ],
  },
  {
    brand: "Porsche",
    models: [
      {
        id: createUniqueId(),
        name: "911",
        transmission: "Automatic",
        fuelType: "Petrol",
        seatNumbers: 4,
        condition: "New",
        price: 100000,
        rentPrice: 500,
      },
      {
        id: createUniqueId(),
        name: "Cayenne",
        transmission: "Automatic",
        fuelType: "Petrol",
        seatNumbers: 5,
        condition: "Used",
        price: 90000,
        rentPrice: 450,
      },
      {
        id: createUniqueId(),
        name: "Macan",
        transmission: "Automatic",
        fuelType: "Petrol",
        seatNumbers: 5,
        condition: "Used",
        price: 80000,
        rentPrice: 400,
      },
      {
        id: createUniqueId(),
        name: "Panamera",
        transmission: "Automatic",
        fuelType: "Petrol",
        seatNumbers: 4,
        condition: "New",
        price: 110000,
        rentPrice: 550,
      },
      {
        id: createUniqueId(),
        name: "Boxster",
        transmission: "Automatic",
        fuelType: "Petrol",
        seatNumbers: 2,
        condition: "Used",
        price: 95000,
        rentPrice: 475,
      },
    ],
  },
  {
    brand: "Tesla",
    models: [
      {
        id: createUniqueId(),
        name: "Model 3",
        transmission: "Automatic",
        fuelType: "Electric",
        seatNumbers: 5,
        condition: "New",
        price: 50000,
        rentPrice: 300,
      },
      {
        id: createUniqueId(),
        name: "Model S",
        transmission: "Automatic",
        fuelType: "Electric",
        seatNumbers: 5,
        condition: "Used",
        price: 80000,
        rentPrice: 500,
      },
      {
        id: createUniqueId(),
        name: "Model X",
        transmission: "Automatic",
        fuelType: "Electric",
        seatNumbers: 7,
        condition: "Used",
        price: 90000,
        rentPrice: 550,
      },
      {
        id: createUniqueId(),
        name: "Model Y",
        transmission: "Automatic",
        fuelType: "Electric",
        seatNumbers: 5,
        condition: "New",
        price: 60000,
        rentPrice: 350,
      },
      {
        id: createUniqueId(),
        name: "Cybertruck",
        transmission: "Automatic",
        fuelType: "Electric",
        seatNumbers: 6,
        condition: "New",
        price: 70000,
        rentPrice: 400,
      },
    ],
  },
  {
    brand: "Ferrari",
    models: [
      {
        id: createUniqueId(),
        name: "458 Italia",
        transmission: "Automatic",
        fuelType: "Petrol",
        seatNumbers: 2,
        condition: "Used",
        price: 250000,
        rentPrice: 1500,
      },
      {
        id: createUniqueId(),
        name: "F8 Tributo",
        transmission: "Automatic",
        fuelType: "Petrol",
        seatNumbers: 2,
        condition: "New",
        price: 300000,
        rentPrice: 1800,
      },
      {
        id: createUniqueId(),
        name: "812 Superfast",
        transmission: "Automatic",
        fuelType: "Petrol",
        seatNumbers: 2,
        condition: "New",
        price: 350000,
        rentPrice: 2000,
      },
      {
        id: createUniqueId(),
        name: "Portofino",
        transmission: "Automatic",
        fuelType: "Petrol",
        seatNumbers: 2,
        condition: "Used",
        price: 280000,
        rentPrice: 1600,
      },
      {
        id: createUniqueId(),
        name: "SF90 Stradale",
        transmission: "Automatic",
        fuelType: "Hybrid",
        seatNumbers: 2,
        condition: "New",
        price: 500000,
        rentPrice: 3000,
      },
    ],
  },
  {
    brand: "Lamborghini",
    models: [
      {
        id: createUniqueId(),
        name: "Huracan",
        transmission: "Automatic",
        fuelType: "Petrol",
        seatNumbers: 2,
        condition: "New",
        price: 300000,
        rentPrice: 1800,
      },
      {
        id: createUniqueId(),
        name: "Aventador",
        transmission: "Automatic",
        fuelType: "Petrol",
        seatNumbers: 2,
        condition: "Used",
        price: 400000,
        rentPrice: 2400,
      },
      {
        id: createUniqueId(),
        name: "Urus",
        transmission: "Automatic",
        fuelType: "Petrol",
        seatNumbers: 5,
        condition: "New",
        price: 350000,
        rentPrice: 2000,
      },
      {
        id: createUniqueId(),
        name: "Sian",
        transmission: "Automatic",
        fuelType: "Hybrid",
        seatNumbers: 2,
        condition: "New",
        price: 3000000,
        rentPrice: 15000,
      },
      {
        id: createUniqueId(),
        name: "Veneno",
        transmission: "Automatic",
        fuelType: "Petrol",
        seatNumbers: 2,
        condition: "Used",
        price: 5000000,
        rentPrice: 25000,
      },
    ],
  },
];

export default CarSpecifications;
